version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    restart: always
    container_name: sdocs_db
    environment:
      - POSTGRES_USER=sdocs
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=sdocs
    ports:
      - "5433:5432"
  admin_back:
    image: sdocs_admin_back
    restart: always
    build: .
    environment:
      - DB_HOST=db
      - DB_NAME=sdocs
      - DB_PW=1234
    container_name: sdocs_admin_back
    command: bash -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py create_superuser &&
      python manage.py loaddata fixtures.json &&
      python manage.py shell < scripts/seeders/admin_panel_init_data.py &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/code
    ports:
      - "8002:8000"
    depends_on:
      - db
    links:
      - db